name: Deploy Vite Static Site to GitHub Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main

  # Also allow manual runs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.3.0 # Adjust this to your node version

      # Install dependencies and build the site
      - name: Install dependencies
        run: npm install

      - name: Build the Vite site
        run: npm run build

      # Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # This is the default output folder for Vite

